-- 1. cleaned_products 먼저 생성
CREATE TABLE cleaned_products (
    goodsNo               BIGINT          PRIMARY KEY,
    플랫폼                  VARCHAR(50),
    카테고리                 VARCHAR(100),
    브랜드                  VARCHAR(100),
    상품명                  VARCHAR(500),
    정가                   BIGINT,
    판매가                  BIGINT,
    할인율                  BIGINT,
    조회수                  BIGINT,
    누적판매수                BIGINT,
    리뷰수                  BIGINT,
    리뷰점수                 BIGINT,
    판매상태                 VARCHAR(20),
    sales_count_suspect   VARCHAR(10),
    sales_count_clean     FLOAT,
    view_count_suspect    VARCHAR(10),
    inactive_candidate    VARCHAR(10)
);

-- 2. cleaned_reviews 생성
CREATE TABLE cleaned_reviews (
    리뷰번호                BIGINT          PRIMARY KEY,
    goodsNo               BIGINT          NOT NULL,
    리뷰타입                VARCHAR(50),
    작성자                  VARCHAR(100),
    리뷰내용                TEXT,
    평점                   FLOAT,
    체험단                  VARCHAR(10),
    구매옵션                VARCHAR(200),
    키                    FLOAT,
    몸무게                  FLOAT,
    성별                   VARCHAR(10),
    작성일                  VARCHAR(50),
    만족도                  VARCHAR(200),
    사진유무                VARCHAR(10),
    도움돼요                BIGINT,
    구매사이즈               VARCHAR(100),
    구매상세                VARCHAR(100),
    연도                   BIGINT,
    월                    BIGINT,
    일                    BIGINT,
    요일                   VARCHAR(10),
    평점_raw               BIGINT,
    만족도_응답여부             VARCHAR(10),
    사이즈                  VARCHAR(50),
    화면대비색감               VARCHAR(50),
    퀄리티                  VARCHAR(50),
    구김                   VARCHAR(50),
    두께감                  VARCHAR(50),
    신축성                  VARCHAR(50),
    색감                   VARCHAR(50),
    보온성                  VARCHAR(50),
    퀄리티_점수               FLOAT,
    보온성_점수               FLOAT,
    신축성_점수               FLOAT,
    두께감_점수               FLOAT,
    구김_점수                FLOAT,
    사이즈_편차               FLOAT,
    사이즈_편차절대             FLOAT,
    화면대비색감_편차            FLOAT,
    화면대비색감_편차절대          FLOAT,
    색감_편차                FLOAT,
    색감_편차절대              FLOAT,
    노출일수                BIGINT,
    일평균_도움돼요지수           FLOAT,
    도움여부                BIGINT,
    FOREIGN KEY (goodsNo) REFERENCES cleaned_products(goodsNo)
);